### ISSUE TITLE
I'm trying to use a local boostrap instead of the web one

### ISSUE THREAD

**Issue by davidthong** [brandoncox/djthonglist#1]
Check the code and see if i did something wrong.

**Comment by brandoncox** [comment]
do you even bootstrap?

**Comment by davidthong** [comment]
I was just messing around with themes.

On Mon, Mar 28, 2016 at 3:44 PM, Brandon Cox notifications@github.com
wrote:

> do you even bootstrap?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/brandoncox/djthonglist/issues/1#issuecomment-202553507

## 

David Thong
dthong@gmail.com

**Comment by davidthong** [comment]
Fixed it. Putting the css in the assets/ stylesheets worked!
